language: node_js
node_js:
  - '10'

services:
  - docker

before_install:
  - npm i @microservices/oms

script:
  - npx oms build
  - |
    output="$(npx oms run --silent message -a name="World" | jq -c .)"
    if [ "$output" != '{"message":"Hello World"}' ] ; then echo "$output"; exit 1; fi
